alias mkdir="mkdir -pv"
alias c="clear"
alias ff="find -type f -path '*src/main*' | fzf | fpp -c idea && wmctrl -a IntelliJ"
alias fv="find -type f -path '*src/main*' | fzf | fpp"
alias yin="yank -- xsel -b"
alias clip="xsel -b"
